http:
  address: ${HTTP_ADDRESS:0.0.0.0:4195}
  enabled: ${HTTP_ENABLED:false}

input:
  broker:
    inputs:
    - label: input_grpc_server
      grpc_server:
        max_in_flight: 50

pipeline:
  processors:
  - log:
      level: INFO
      message: "message passing through benthos"
      fields:
        payload: '${! json() }'

output:
  switch:
    retry_until_success: false
    cases:
      - check: 'errored()'
        output:
          reject: "Message failed due to: ${! error() }"
      - check: '!errored()'
        output:
          stdout: {}

metrics:
  prometheus: {}

logger:
  level: ${LOGGER_LEVEL:DEBUG}
  add_timestamp: ${LOGGER_ADD_TIMESTAMP:true}
  format: ${LOGGER_FORMAT:logfmt}
  static_fields:
    '@service': benthos_grpc
